### ISSUE TITLE
拖动的时候，如果手指出了控件之外再离开，block不触发的，获取不了分数了

### ISSUE THREAD

**Issue by tanjieaa** [iOS-ZZ/ZZTools#1]

**Comment by iOS-ZZ** [comment]
你好, demo亲测真机&模拟器都没有发生如上问题, block是在系统的- (void)touchesEnded:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {}方法中调用的, 只要传入了block就会调用, 如果确认存在您说的传了block但不回调, 那应该是该- (void)touchesEnded:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event{}方法没有被系统调用, 可以附上一个demo重现问题吗, 邮箱: 1156858877@qq.com

**Comment by iOS-ZZ** [comment]
你好, 暂时关闭问题了哦, 如果确定存在, 请发送demo至邮箱: 1156858877@qq.com
